version: '3.8'

services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
        USE_CUDA: true
        USE_OLLAMA: false
        ICLOUD_API_BASE_URL: 'http://192.168.1.104:3003'
      dockerfile: Dockerfile.dev
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    init: true
    container_name: webui
    volumes:
      - open-webui:/app/backend/data
      - ./src:/app/src
      - ./umc:/app/umc
      - ./backend:/app/backend
      - ./static:/app/static
    networks:
      ollama_net:
        ipv4_address: 172.29.0.10
    ports:
      - 11222:8080
    environment:
      - PORT=8080
      - ENV=dev
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_NAME=U-AI'
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11435'
      - 'OPENAI_API_BASE_URLS=http://host.docker.internal:10016 ; http://172.29.0.35:9099'
      - 'OPENAI_API_KEYS= sadfjlkwer.msdf ; 0p3n-w3bu!'
    extra_hosts:
      - "host.docker.internal:192.168.1.105"
    # Allow access to host network
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    restart: unless-stopped
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: all
              capabilities:
                - gpu

  pipelines:
    container_name: pipelines
    image: ghcr.io/open-webui/pipelines:main
    restart: always
    networks:
      ollama_net:
        ipv4_address: 172.29.0.35
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9099:9099
    volumes:
      - pipelines:/app/pipelines
    environment:
      - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"

  #! 沒辦法從 Docker Hub 下載，所以先不啟用
  # whisper:
  #   container_name: whisper
  #   image: onerahmet/openai-whisper-asr-webservice:latest-gpu
  #   # GPU support
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: ${OLLAMA_GPU_DRIVER-nvidia}
  #             count: all
  #             capabilities:
  #               - gpu
  #   environment:
  #     - ASR_MODEL_PATH=/tmp/whisper
  #     # 以下是模型下載地址
  #     # 請存放到 ./whisper-model 目錄下，並修改 ASR_MODEL 為下載的模型名稱
  #     # "tiny.en": "https://openaipublic.azureedge.net/main/whisper/models/d3dd57d32accea0b295c96e26691aa14d8822fac7d9d27d5dc00b4ca2826dd03/tiny.en.pt",
  #     # "tiny": "https://openaipublic.azureedge.net/main/whisper/models/65147644a518d12f04e32d6f3b26facc3f8dd46e5390956a9424a650c0ce22b9/tiny.pt",
  #     # "base.en": "https://openaipublic.azureedge.net/main/whisper/models/25a8566e1d0c1e2231d1c762132cd20e0f96a85d16145c3a00adf5d1ac670ead/base.en.pt",
  #     # "base": "https://openaipublic.azureedge.net/main/whisper/models/ed3a0b6b1c0edf879ad9b11b1af5a0e6ab5db9205f891f668f8b0e6c6326e34e/base.pt",
  #     # "small.en": "https://openaipublic.azureedge.net/main/whisper/models/f953ad0fd29cacd07d5a9eda5624af0f6bcf2258be67c92b79389873d91e0872/small.en.pt",
  #     # "small": "https://openaipublic.azureedge.net/main/whisper/models/9ecf779972d90ba49c06d968637d720dd632c55bbf19d441fb42bf17a411e794/small.pt",
  #     # "medium.en": "https://openaipublic.azureedge.net/main/whisper/models/d7440d1dc186f76616474e0ff0b3b6b879abc9d1a4926b7adfa41db2d497ab4f/medium.en.pt",
  #     # "medium": "https://openaipublic.azureedge.net/main/whisper/models/345ae4da62f9b3d59415adc60127b97c714f32e89e936602e85993674d08dcb1/medium.pt",
  #     # "large-v1": "https://openaipublic.azureedge.net/main/whisper/models/e4b87e7e0bf463eb8e6956e646f1e277e901512310def2c24bf0e11bd3c28e9a/large-v1.pt",
  #     # "large-v2": "https://openaipublic.azureedge.net/main/whisper/models/81f7c96c852ee8fc832187b0132e569d6c3065a3252ed18e56effd0b6a73e524/large-v2.pt",
  #     # "large-v3": "https://openaipublic.azureedge.net/main/whisper/models/e5b1a55b89c1367dacf97e3e19bfd829a01529dbfdeefa8caeb59b3f1b81dadb/large-v3.pt",
  #     # "large": "https://openaipublic.azureedge.net/main/whisper/models/e5b1a55b89c1367dacf97e3e19bfd829a01529dbfdeefa8caeb59b3f1b81dadb/large-v3.pt",
  #     - ASR_MODEL=base
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./whisper-model:/tmp/whisper

volumes:
  open-webui: {}
  pipelines:

networks:
  ollama_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

